  nft_marketplace_config:
    name: wapal
    event_model_mapping:
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingPlacedEvent: place_listing
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingCanceledEvent: cancel_listing
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingFilledEvent: fill_listing
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferPlacedEvent: place_token_offer
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferCanceledEvent: cancel_token_offer
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferFilledEvent: fill_token_offer
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferPlacedEvent: place_collection_offer
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferCanceledEvent: cancel_collection_offer
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferFilledEvent: fill_collection_offer
    events:
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingPlacedEvent:
        event_fields:
          "$.listing":
            - table: nft_marketplace_activities
              column: listing_id
            - table: current_nft_marketplace_listings
              column: listing_id
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
            - table: current_nft_marketplace_listings
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_listings
              column: price
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_listings
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingCanceledEvent:
        event_fields:
          "$.collection.vec[0].inner":
            - table: nft_marketplace_activities
              column: collection_id
            - table: current_nft_marketplace_listings
              column: collection_id
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_listings
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_listings
              column: price
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
            - table: current_nft_marketplace_listings
              column: seller
          "$.token_amount":
            - table: nft_marketplace_activities
              column: token_amount
            - table: current_nft_marketplace_listings
              column: token_amount
          "$.listing":
            - table: nft_marketplace_activities
              column: listing_id
            - table: current_nft_marketplace_listings
              column: listing_id
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingFilledEvent:
        event_fields:
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_listings
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_listings
              column: price
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
            - table: current_nft_marketplace_listings
              column: seller
          "$.token_amount":
            - table: nft_marketplace_activities
              column: token_amount
            - table: current_nft_marketplace_listings
              column: token_amount
          "$.listing":
            - table: nft_marketplace_activities
              column: listing_id
            - table: current_nft_marketplace_listings
              column: listing_id
            #  v1
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
            - table: current_nft_marketplace_listings
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
            - table: current_nft_marketplace_listings
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_id
            - table: current_nft_marketplace_listings
              column: collection_id
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
            - table: current_nft_marketplace_listings
              column: buyer
          "$.owner":
            - table: nft_marketplace_activities
              column: seller
            - table: current_nft_marketplace_listings
              column: seller              
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferPlacedEvent:
        event_fields:
          "$.token_offer":
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_token_offers
              column: offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
            - table: current_nft_marketplace_token_offers
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_token_offers
              column: price
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_token_offers
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
            - table: current_nft_marketplace_token_offers
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferCanceledEvent:
        event_fields:
          "$.token_offer":
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_token_offers
              column: offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
            - table: current_nft_marketplace_token_offers
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_token_offers
              column: price
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_token_offers
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
            - table: current_nft_marketplace_token_offers
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferFilledEvent:
        event_fields:
          "$.token_offer":
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_token_offers
              column: offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
            - table: current_nft_marketplace_token_offers
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
            - table: current_nft_marketplace_token_offers
              column: price
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
            - table: current_nft_marketplace_token_offers
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
            - table: current_nft_marketplace_token_offers
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferCanceledEvent:
        event_fields:
          "$.collection_offer": 
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_collection_offers
              column: collection_offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
            - table: current_nft_marketplace_collection_offers
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.remaining_token_amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.collection_metadata.collection.vec[0].inner":
            - table: nft_marketplace_activities
              column: collection_id
          "$.collection_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.collection_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferFilledEvent:
        event_fields:
          "$.collection_offer":
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_collection_offers
              column: collection_offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_metadata.token.vec[0].inner":
            - table: nft_marketplace_activities
              column: token_data_id
          "$.token_metadata.token_name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
      0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferPlacedEvent:
        event_fields:
          "$.collection_offer":
            - table: nft_marketplace_activities
              column: offer_id
            - table: current_nft_marketplace_collection_offers
              column: collection_offer_id
          "$.purchaser":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_amount":
            - table: nft_marketplace_activities
              column: token_amount
            - table: current_nft_marketplace_collection_offers
              column: remaining_token_amount
          "$.collection_metadata.collection.vec[0].inner":
            - table: nft_marketplace_activities
              column: collection_id
          "$.collection_metadata.creator_address":
            - table: nft_marketplace_activities
              column: creator_address
          "$.collection_metadata.collection_name":
            - table: nft_marketplace_activities
              column: collection_name